name: Run Databricks notebook on contract change

on:
  push:
    paths:
      - datacontracts/orders/datacontract.uc2.yaml
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Databricks CLI (official action)
      - uses: databricks/setup-cli@main

      - name: Trigger existing Databricks job
        run: |
          databricks jobs run-now --job-id "${{ vars.DATABRICKS_JOB_ID }}" --no-wait
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}   # e.g. https://<workspace>.cloud.databricks.com
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }} # PAT or SP token with permission to run the job
